apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: wordpress-mysql-backup
  namespace: demo
spec:
  repository:
    name: s3-mysql
  schedule: "*/5 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: AppBinding
      name: sample-mysql
  task:
    name: mysql-backup-8.0.14
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
