apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: sample-mysql-restore
  namespace: wordpress
  labels:
    kubedb.com/kind: MySQL # this label is mandatory if you are using KubeDB to deploy the database.
spec:
  task:
    name: mysql-restore-8.0.14
  repository:
    name: s3-mysql
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: sample-mysql
  rules:
    - snapshots: [latest]
