apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: wordpress-backup
  namespace: demo
spec:
  repository:
    name: s3-repo
  schedule: "*/5 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: wordpress
    volumeMounts:
    - name: wordpress-persistent-storage
      mountPath: /var/www/html
    paths:
    - /var/www/html
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
