apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: s3-repo
  namespace: wordpress
spec:
  backend:
    s3:
      endpoint: http://172.17.0.2:9000
      bucket: kubedemo
      prefix: /wordpress
    storageSecretName: s3-secret
