apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: wordpress-restore
  namespace: wordpress
spec:
  repository:
    name: s3-repo
  rules:
  - paths:
    - /var/www/html
  target: # target indicates where the recovered data will be stored
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: wordpress
    volumeMounts:
    - name:  wordpress-persistent-storage
      mountPath:  /var/www/html
